// <auto-generated />
namespace PSTodos.Infrastructure.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FixErrors : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixErrors));
        
        string IMigrationMetadata.Id
        {
            get { return "201702132056195_FixErrors"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
